### ISSUE TITLE
Get The Spodify API To Work

### ISSUE THREAD

**Issue by Orange-Peel-Assassin** [OPA-inc/Rock-Class-Time-Stamp#6]
- [ ] #6 [API] User Info
- [ ] #7 [API] Timestamp Button
- [ ] #8 [API]  Albume Art
